config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :contact
  root to: "contact#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user

  validates :first_name, presence: true
  validates :first_name, uniqueness: { scope: :last_name,
    message: "someone else has that full name", case_sensitive: false }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }


  def get_tags
    tag_list.split(',')
  end

  def set_tags(tag_arr)
    self.update!(tag_list: tag_arr.join(','))
  end

  def add_tag(new_tag)
    tag_arr = get_tags
    tag_arr << new_tag
    set_tags(tag_arr)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
	def index
		initialize_all_contacts
	end

	def create
		new_contact = Contact.new(contact_params)
		new_contact.user = current_user
		if new_contact.save
			flash[:notice] = "You have successfully added a new contact!"
			redirect_to contact_index_path
		else
			flash[:alert] = "Something went wrong with your form, check hints below each field."
			initialize_all_contacts
			render :index
		end
	end

	def edit
	end

	def update
		contact = Contact.find(params[:id]) 
		if contact.update(contact_params)
			redirect_to contact_index_path
		else
			initialize_all_contacts
			render :index
		end
	end

	def destroy
		contact = Contact.find(params[:id])
		contact.destroy!
		redirect_to contact_index_path
	end

	private

	def initialize_all_contacts
		search_term = ""
		if params[:search]
			search_term = params[:search][:search]
		end

		@all_contacts = filter_contacts(current_user.contacts, search_term)
	end

	def filter_contacts(contacts, query)
		key = "%#{query}%"
		contacts.where('first_name LIKE :query OR last_name LIKE :query OR tag_list LIKE :query', query: key).order(:last_name)
	end

	def contact_params
		params.require(:contact).permit(:first_name, :last_name, :phone_number, :email, :address, :tag_list)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/_card.html.erb
<div class="form-box has-success your-contacts">
  <%= simple_form_for(contact) do |f| %>
    <%= f.error_notification %>
    <%= f.input :first_name, value: contact.first_name, hint: 'required' %>
    <%= f.input :last_name, value: contact.last_name, hint: 'full name must be unique' %>
    <%= f.input :phone_number, value: contact.phone_number %>
    <%= f.input :email, value: contact.email, hint: 'email must be valid format' %>
    <%= f.input :address, value: contact.address %>
    <%= f.input :tag_list, value: contact.get_tags, hint: 'tags must be comma seperated, (no space)' %>
    <%= f.button :submit, value: 'Update', class: "btn btn-success" %>
    <%= link_to "Delete", contact_path(contact), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
  <% end %>
</div>

app/views/contact/index.html.erb
<div class="main text-center">
    <h1>Your Address Book</h1>
    <%= link_to "Log-Out", destroy_user_session_path, method: :delete, class: "btn btn-info" %>
</div>

<div class="wrapper">
  <div class="container text-center">
    <div class="row">
      <div class="col-sm-6 col-xs-12">
        <h3>Add a new person to your contact list!</h3>
        <div class="form-box has-warning your-contacts">
          <%= simple_form_for(Contact.new, :url=> {:action=>'create'}) do |f| %>
            <%= f.error_notification %>
            <%= f.input :first_name, placeholder: 'John', hint: 'required' %>
            <%= f.input :last_name, placeholder: 'Doe', hint: 'full name must be unique'%>
            <%= f.input :phone_number, placeholder: '(514)435-5678'%>
            <%= f.input :email, placeholder: 'john@gmail.com', hint: 'email must be valid format' %>
            <%= f.input :address, placeholder: '294 Saint-Catherine St W, Montreal, Canada' %>
            <%= f.input :tag_list, placeholder: 'family,client', hint: 'tags must be comma seperated, (no space)' %>
            <%= f.button :submit, value: 'Submit', class: "btn btn-success" %>
          <% end %>
        </div>
      </div>
      <div class="col-sm-6 col-xs-12">
        <h3>SEARCH!!!</h3>
        <div class="your-contacts">
          <h5>Filter and search your contacts by first name, last name, or tag!</h5>
          <%= simple_form_for :search, method: 'get', wrapper_html: :inline_form, html:{class: 'form-inline materialInlineForm', id: 'contactSearchForm'} do |f| %>
            <%= f.input :search, placeholder: 'name or tag', label: false, input_html: { class: 'input-field search-query' }, prompt: 'Type' %>
            <%= f.submit "Find!", :class => "btn btn-primary btn-search" %>
          <% end %>
        </div>
      </div>
    </div>

    <div class="row">
      <h3>Your Contacts</h3>
      <% @all_contacts.each do |contact| %>
        <div class="col-sm-6 col-xs-12">
          <%= render 'card', contact: contact %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleContactApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>